backend:
  name: github
  repo: edburtnieks/edburtnieks

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'examples'
    label: 'Example'
    folder: 'content/examples'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Live site',
          name: 'liveSite',
          widget: 'string',
          required: false,
          default: '',
        }
      - {
          label: 'Source',
          name: 'source',
          widget: 'string',
          required: false,
          default: '',
        }
  - name: 'frontend-mentor-challenges'
    label: 'Frontend Mentor Challenge'
    folder: 'content/frontend-mentor-challenges'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }
