backend:
  name: github
  repo: edburtnieks/edburtnieks

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "examples"
    label: "Example"
    folder: "content/examples"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - label: "Links"
        name: "links"
        widget: "list"
        collapsed: false
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
      - { label: "Technology stack", name: "technologyStack", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image Alt", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "frontend-mentor-challenges"
    label: "Frontend Mentor Challenge"
    folder: "content/frontend-mentor-challenges"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Links", name: "links", widget: "boolean", default: true }
      - { label: "Challenge link", name: "challengeLink", widget: "string" }
      - { label: "Solution link", name: "solutionLink", widget: "string" }
      - { label: "Live site link", name: "liveSiteLink", widget: "string" }
      - {
          label: "GitHub repository",
          name: "gitHubRepositoryLink",
          widget: "string",
        }
      - { label: "Technology stack", name: "technologyStack", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image Alt", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "skills"
    label: "Skills"
    file: "content/skills.yml"
    fields:
      - label: "Skills"
        name: "skills"
        widget: "list"
        fields:
          - { label: "Skills", name: "skills", widget: "list" }
          - { label: "Category", name: "category", widget: "string" }
