backend:
  name: github
  repo: edburtnieks/edburtnieks

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
