backend:
  name: git-gateway

publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'Blog'
    create: true
    folder: '_posts/blog'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

media_folder: 'static/images/uploads'

media_library:
  name: ''
