backend:
  name: github
  repo: edburtnieks/edburtnieks

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "examples"
    label: "Example"
    folder: "content/examples"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - label: "Links"
        name: "links"
        widget: "list"
        collapsed: false
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
      - { label: "Technology stack", name: "technologyStack", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image Alt", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "general"
    label: "General"
    files:
      - name: "skills"
        label: "Skills"
        file: "content/skills.yml"
        fields:
          - label: "Skills"
            name: "skills"
            widget: "list"
            collapsed: false
            fields:
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Skills", name: "skills", widget: "list" }
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{fields.slug}}"
    sortableFields: ["createdAt"]
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Part", name: "part", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: 'Created at', name: 'createdAt', widget: 'datetime', dateFormat: "YYYY-MM-DD" }
      - { label: "Previous post title", name: "previousPostTitle", widget: "string" }
      - { label: "Previous post link", name: "previousPostLink", widget: "string" }
      - { label: "Next post title", name: "nextPostTitle", widget: "string" }
      - { label: "Next post link", name: "nextPostLink", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
